import React, { useState } from 'react';
import styled from 'styled-components';
import { useTranslation } from 'react-i18next';
import { ColumnFlex, RowFlex } from '@ui/components/Flex';
import { ButtonPrimary } from '@ui/components/buttons/ButtonPrimary';
import { FieldCheck } from '@ui/components/inputs/FieldCheck';
import { Popover } from '@ui/components/Popover';
import { useFloatingDropdown } from '@ui/components/Dropdown';
import AISVG from '@ui/atoms/icons/AI-16.svg';
import TriangleArrowDownSVG from '@ui/atoms/icons/TriangleArrowDown-12.svg';
import { IntentSettings } from './IntentSettings';

/**
 * V3 fork of V2's GenerateQueriesPanel (frontend-only, NOT for production), per Figma node
 * 5170:18303 ("Form dropdown"): the always-open "Generate queries from intent" card is replaced
 * with an inline "Generate queries" dropdown trigger + popover (no nested modal) that sits next
 * to "+ Add query" (see QueriesSettings). Both the trigger and the popover's own action button are
 * the real design-system `ButtonPrimary` at small size (per Figma node 5206:1466's mockup and the
 * component library's own node 4436:6661), inheriting every state — hover/active/disabled/loading
 * — from the real component untouched. One deliberate departure from that Figma mock, per explicit
 * request: the character counter is kept inset in the textarea (Figma's mock doesn't show one) —
 * see IntentSettings, whose own helper line under the textarea otherwise matches the mock exactly
 * (a single plain-gray tip, not a blue tip box that swaps to a different message past 80 chars).
 * There's no
 * "Generating in {LANG}" tag — the language selector above the query list (see
 * LanguageSelector/QueriesSettings) is the single source of truth for "which language". An
 * "Add to all languages" checkbox appears only when the answer has more than one language; when
 * checked, generation targets every language instead of just the current one. Generated queries
 * are deduped against the existing list (case/punctuation/whitespace-insensitive) before being
 * appended straight into the query list — no staged +/- review queue — and get tagged as
 * AI-generated by the parent dialog (see onAddGeneratedQueries in AddAnswerDialog/
 * EditAnswerDialog) so QueriesSettings can show the AI icon + tooltip. Generation is mocked
 * locally with a fixed delay.
 */
const MOCK_GENERATION_DELAY_MS = 1400;

// Strips the "when/if the user ..." lead-in so what's left is the actual topic, not the whole
// instruction sentence (e.g. "Show this answer when the user explicitly requests to speak to a
// real person" -> "speak to a real person").
const LEAD_IN_REGEX =
  /^(show this answer\s+)?(when|if)\s+(the\s+)?(a\s+)?(user|customer|client)s?\s+(is\s+|explicitly\s+)?(asks?\s+(about\s+)?|wants?\s+to\s+|needs?\s+to\s+|requests?\s+to\s+|tries?\s+to\s+|attempts?\s+to\s+|can(no|')?t\s+|cannot\s+|has\s+(a\s+)?problems?\s+with\s+)?/i;

// Drops a leading filler clause from a split-out segment (e.g. "expressing frustration that the
// bot isn't helping" -> "the bot isn't helping").
const CLAUSE_FILLER_REGEX =
  /^(expressing\s+frustration\s+that\s+|expressing\s+that\s+|feeling\s+frustrated\s+that\s+|saying\s+that\s+|mentioning\s+that\s+|indicating\s+that\s+)/i;

// Real intents are one long instruction; queries are short. Split on the connectors people use to
// list alternatives or add a clause, so each fragment can become its own short query instead of
// the whole sentence getting stuffed into every template.
const SEGMENT_SPLIT_REGEX =
  /,|\bor\b|\band\b|\bafter\b|\bbefore\b|\bunless\b|\balthough\b|\beven though\b|\bso that\b|\bin order to\b|\bespecially when\b|\bparticularly when\b|\bespecially if\b|\bparticularly if\b/i;

const MAX_SEGMENT_WORDS = 7;

const VERB_STARTER_SET = new Set([
  'speak', 'talk', 'contact', 'connect', 'reset', 'cancel', 'change', 'update', 'access', 'get',
  'request', 'use', 'enable', 'disable', 'find', 'delete', 'remove', 'add', 'create', 'edit',
  'export', 'import', 'download', 'upload', 'share', 'invite', 'sign', 'log', 'save', 'submit',
  'publish', 'send', 'call', 'schedule', 'book', 'pay', 'refund', 'unsubscribe', 'restart',
  'install', 'uninstall', 'verify', 'confirm', 'activate', 'deactivate', 'merge', 'export',
]);

const capitalize = (text: string) => text.charAt(0).toUpperCase() + text.slice(1);

const extractTopicPhraseList = (intentDescription: string): string[] => {
  const stripped = intentDescription.trim().replace(LEAD_IN_REGEX, '').replace(/[.?!]+$/, '');
  const rawSegmentList = stripped
    .split(SEGMENT_SPLIT_REGEX)
    .map(segment => segment.trim())
    .filter(Boolean);
  const segmentList = (rawSegmentList.length ? rawSegmentList : [stripped])
    .map(segment => segment.replace(CLAUSE_FILLER_REGEX, '').trim())
    .map(segment => segment.split(/\s+/).slice(0, MAX_SEGMENT_WORDS).join(' '))
    .filter(segment => segment.length > 1);
  return segmentList.length
    ? segmentList
    : [intentDescription.trim().split(/\s+/).slice(0, MAX_SEGMENT_WORDS).join(' ')];
};

const VERB_TEMPLATE_LIST: ((segment: string) => string)[] = [
  segment => `How do I ${segment}?`,
  segment => `I want to ${segment}`,
  segment => `Can I ${segment}?`,
  segment => `Help me ${segment}`,
];

const NOUN_TEMPLATE_LIST: ((segment: string) => string)[] = [
  segment => `Talk to ${segment}`,
  segment => `Need ${segment}`,
  segment => `Connect me to ${segment}, please`,
  segment => `${capitalize(segment)} now`,
];

export const buildMockSuggestionList = (intentDescription: string, language: string): string[] => {
  const segmentList = extractTopicPhraseList(intentDescription);
  const queryListBySegment = segmentList.map(segment => {
    const firstWord = segment.split(/\s+/)[0]?.toLowerCase();
    const templateList = VERB_STARTER_SET.has(firstWord) ? VERB_TEMPLATE_LIST : NOUN_TEMPLATE_LIST;
    return templateList.map(template => template(segment));
  });

  // Round-robin across segments (one template from each per round) so short variety from every
  // segment shows up early, instead of exhausting one segment's templates before the next.
  const maxTemplateCount = Math.max(...queryListBySegment.map(list => list.length));
  const suggestionList: string[] = [];
  for (let templateIndex = 0; templateIndex < maxTemplateCount; templateIndex += 1) {
    queryListBySegment.forEach(list => {
      if (list[templateIndex]) suggestionList.push(list[templateIndex]);
    });
  }

  const dedupedList = Array.from(new Set(suggestionList)).slice(0, 10);
  return language === 'en'
    ? dedupedList
    : dedupedList.map(suggestion => `${suggestion} (${language.toUpperCase()})`);
};

// Normalizes a query for near-duplicate comparison: case, punctuation, and leading/trailing
// whitespace shouldn't matter — "Can't save?" and "cant save" are the same suggestion twice.
const normalizeForDedup = (text: string): string =>
  text
    .trim()
    .toLowerCase()
    .replace(/[.,!?;:'"()]/g, '')
    .replace(/\s+/g, ' ');

/** Builds one generated-query list per language: the current language gets the plain suggestion, others get a translated-looking variant. */
export const buildQueryTextListByLanguage = (
  intentDescription: string,
  currentLanguage: string,
  languageList: string[],
  existingQueryList: string[]
): { [language: string]: string[] } => {
  const existingQueryNormalizedSet = new Set(existingQueryList.map(normalizeForDedup));
  // De-dupe against the existing list AND within the freshly-generated batch itself (the
  // round-robin template pass above can occasionally produce near-identical phrasings).
  const seenNormalizedSet = new Set<string>();
  const baseTextList = buildMockSuggestionList(intentDescription, currentLanguage).filter(suggestion => {
    const normalized = normalizeForDedup(suggestion);
    if (existingQueryNormalizedSet.has(normalized) || seenNormalizedSet.has(normalized)) return false;
    seenNormalizedSet.add(normalized);
    return true;
  });
  return Object.fromEntries(
    languageList.map(language => [
      language,
      baseTextList.map(text => (language === currentLanguage ? text : `${text} (${language.toUpperCase()})`)),
    ])
  );
};

const PopoverContent = styled(ColumnFlex)`
  width: 450px;
`;

// Figma nests two padding layers here — an outer 8px "Form section" wrap around an inner
// Form with its own 8px/12px/16px (top/sides/bottom) — collapsed into one div, so the effective
// padding is the sum of both: 16px top, 20px sides, 24px bottom.
const FormSection = styled(ColumnFlex)`
  padding: 16px 20px 24px;
  gap: 16px;
`;

const PopoverTitle = styled.span`
  display: flex;
  align-items: center;
  gap: 8px;
  ${({ theme }) => theme.typography.uiElementStrong};
  color: ${({ theme }) => theme.color.textDark};

  svg {
    flex: none;
  }

  /* Confirmed against the actual Figma asset (node 5170:20536): this title icon is #F74D7E
     (theme.color.iconPink), not the AI-16 source file's own baked-in purple fill. */
  svg path {
    fill: ${({ theme }) => theme.color.iconPink};
  }
`;

const PopoverDivider = styled.div`
  height: 1px;
  width: 100%;
  flex: none;
  background: ${({ theme }) => theme.color.borderSubtle};
`;

const FooterRow = styled(RowFlex)`
  padding: 16px 24px 16px 16px;
`;

interface GenerateQueriesDropdownProps {
  currentLanguage: string;
  /** Full language list for this answer — drives whether "Add to all languages" is offered. */
  languageList: string[];
  isCustomMessageType: boolean;
  existingQueryList: string[];
  onAddQueries: (queryTextListByLanguage: { [language: string]: string[] }) => void;
  intentDescription: string;
  onIntentDescriptionChange: (intentDescription: string) => void;
}

export const GenerateQueriesDropdown = ({
  currentLanguage,
  languageList,
  isCustomMessageType,
  existingQueryList,
  onAddQueries,
  intentDescription,
  onIntentDescriptionChange,
}: GenerateQueriesDropdownProps) => {
  const { t } = useTranslation();
  const [isGenerating, setIsGenerating] = useState(false);
  // Modal Button Guidelines: Generate is never disabled — clicking with an empty intent triggers
  // inline validation on the field instead.
  const [isValidationTriggered, setIsValidationTriggered] = useState(false);
  const [addToAllLanguages, setAddToAllLanguages] = useState(false);
  const hasMultipleLanguages = languageList.length > 1;

  const { isOpen, close, triggerProps, floatingProps } = useFloatingDropdown<HTMLButtonElement>({
    placement: 'bottom-start',
    widthPx: 450,
    minWidthRatio: 0,
    maxWidthRatio: 0,
    closingKeyList: ['Escape'],
  });

  const isIntentValid = !!intentDescription.trim();

  const onGenerate = () => {
    if (!isIntentValid) {
      setIsValidationTriggered(true);
      return;
    }
    setIsGenerating(true);
    setTimeout(() => {
      // Single language by default — the selector above the query list is the source of truth
      // for "which language" — unless "Add to all languages" is checked (only offered when the
      // answer actually has more than one language).
      const targetLanguageList = addToAllLanguages && hasMultipleLanguages ? languageList : [currentLanguage];
      onAddQueries(buildQueryTextListByLanguage(intentDescription, currentLanguage, targetLanguageList, existingQueryList));
      setIsGenerating(false);
      setIsValidationTriggered(false);
      setAddToAllLanguages(false);
      // Cleared (not just closed) so the field is empty and ready for a fresh intent the next time
      // this popover opens — otherwise the old text would linger and get deduped away instead of
      // producing new queries on a second generation.
      onIntentDescriptionChange('');
      close();
    }, MOCK_GENERATION_DELAY_MS);
  };

  return (
    <>
      <ButtonPrimary
        {...triggerProps}
        size="small"
        iconLeft={<AISVG />}
        iconRight={<TriangleArrowDownSVG />}
        isPressed={isOpen}
        data-cy="generateQueriesTrigger"
      >
        {t('AiSources.GuidedAnswers.V3.GenerateTriggerButton')}
      </ButtonPrimary>
      {isOpen && (
        <Popover {...floatingProps} isFocusLocked data-cy="generateQueriesPopover">
          <PopoverContent>
            <FormSection>
              <PopoverTitle>
                <AISVG />
                {t('AiSources.GuidedAnswers.V3.PopoverTitle')}
              </PopoverTitle>
              <IntentSettings
                intentDescription={intentDescription}
                onIntentDescriptionChange={onIntentDescriptionChange}
                showValidation={isValidationTriggered}
              />
            </FormSection>
            <PopoverDivider />
            <FooterRow
              alignItems="center"
              justifyContent={hasMultipleLanguages ? 'space-between' : 'flex-end'}
            >
              {hasMultipleLanguages && (
                <FieldCheck
                  type="checkbox"
                  checked={addToAllLanguages}
                  onChangeChecked={setAddToAllLanguages}
                  label={t('AiSources.GuidedAnswers.V3.AddToAllLanguages')}
                  data-cy="addToAllLanguagesCheckbox"
                />
              )}
              <ButtonPrimary size="small" onClick={onGenerate} isLoading={isGenerating} data-cy="generateActionButton">
                {t(
                  isGenerating
                    ? 'AiSources.GuidedAnswers.V3.GeneratingActionButton'
                    : 'AiSources.GuidedAnswers.V3.GenerateActionButton'
                )}
              </ButtonPrimary>
            </FooterRow>
          </PopoverContent>
        </Popover>
      )}
    </>
  );
};
